spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_demo?useSSL=false
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  enhance:
    store:
      file: classpath:/enhance/keystore.jks
      password: nguyenvt2
    key:
      alias: nguyenvt2@fsoft.com.vn
      password: nguyenvt2
